/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 satellite.gltf --transform
Author: Andrey Borisov (https://sketchfab.com/Andrey_Borisov)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/satellite-draft-xyz-homework-bb05cc3aad6e4a589f6ee8d837bdfce5
Title: Satellite - Draft XYZ Homework
*/

import React, { useRef, useEffect } from 'react'
import { useFrame, useThree } from '@react-three/fiber'
import { useGLTF } from '@react-three/drei'
import gsap from 'gsap';
import Sat from '/src/assets/models/satellite-transformed.glb'

export default function Model(props) {
  const { nodes, materials } = useGLTF(Sat)

  const earth = useRef();

  const { camera } = useThree();

  useEffect(() => {
    function handleMouseMove(event) {
      const { clientX, clientY } = event;

      const mouse = {
        x: (clientY / window.innerHeight) * Math.PI - Math.PI / 2,
        y: (clientX / window.innerWidth) * Math.PI * 2,
        z: 0,
      };

      gsap.to(earth.current.rotation, {
        y: -mouse.y * 0.4,
        x: mouse.x * 0.2,
        duration: 3
      });
    }

    window.addEventListener('mousemove', handleMouseMove);

    return () => {
      window.removeEventListener('mousemove', handleMouseMove);
    };
  }, []);

  useFrame(() => {
    earth.current.rotation.y += 0.001
  });

  return (
    <group ref={earth} {...props} dispose={null}>
      <group position={[30, 0, 10]} rotation={[-2.12, -0.65, 0.28]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[-14.07, 37.74, 0]} rotation={[0.43, 0.17, -0.56]} scale={1}>
            <group position={[3.96, 2.47, -0.08]} scale={0.42}>
              <mesh geometry={nodes.pCube109_Sput_ST_Metal_Dark_0.geometry} material={materials.Sput_ST_Metal_Dark} position={[-3.96, -36.78, -43.35]} />
              <mesh geometry={nodes.pCube156_Sput_ST_Metal_light_0.geometry} material={materials.Sput_ST_Metal_light} position={[-9.38, -6.6, -1.12]} scale={2.37} />
            </group>
            <group position={[3.96, 2.75, 0.42]} scale={0.42}>
              <mesh geometry={nodes.pCube109_Sput_ST_Metal_Dark_0_1.geometry} material={materials.Sput_ST_Metal_Dark} position={[-3.96, -36.78, -43.35]} />
              <mesh geometry={nodes.pCube156_Sput_ST_Metal_light_0_1.geometry} material={materials.Sput_ST_Metal_light} position={[-9.38, -6.6, -1.12]} scale={2.37} />
            </group>
            <mesh geometry={nodes.pCylinder43_Sput_ST_Metal_Dark_0.geometry} material={materials.Sput_ST_Metal_Dark} />
            <mesh geometry={nodes.pCylinder198_Sput_ST_Metal_light_0.geometry} material={materials.Sput_ST_Metal_light} />
            <mesh geometry={nodes.pCylinder197_Sput_ST_Metal_light_0.geometry} material={materials.Sput_ST_Metal_light} />
            <mesh geometry={nodes.pCube160_Sput_ST_Metal_Dark_02_0.geometry} material={materials.Sput_ST_Metal_Dark_02} />
            <mesh geometry={nodes.pCube161_Sput_ST_Metal_Dark_02_0.geometry} material={materials.Sput_ST_Metal_Dark_02} />
            <mesh geometry={nodes.pCylinder43_Sput_ST_Metal_Dark_0_1.geometry} material={materials.Sput_ST_Metal_Dark} />
            <mesh geometry={nodes.pCylinder198_Sput_ST_Metal_light_0_1.geometry} material={materials.Sput_ST_Metal_light} />
            <mesh geometry={nodes.pCylinder197_Sput_ST_Metal_light_0_1.geometry} material={materials.Sput_ST_Metal_light} />
            <mesh geometry={nodes.pCube160_Sput_ST_Metal_Dark_02_0_1.geometry} material={materials.Sput_ST_Metal_Dark_02} />
            <mesh geometry={nodes.pCube161_Sput_ST_Metal_Dark_02_0_1.geometry} material={materials.Sput_ST_Metal_Dark_02} />
            <group position={[5.15, -2.33, 0]} rotation={[0, 0, Math.PI / 4]}>
              <mesh geometry={nodes.pCube127_Sput_ST_Metal_light_0.geometry} material={materials.Sput_ST_Metal_light} />
              <mesh geometry={nodes.polySurface14_Sput_ST_Metal_Dark_0.geometry} material={materials.Sput_ST_Metal_Dark} />
              <mesh geometry={nodes.polySurface12_Sput_ST_Metal_Dark_0.geometry} material={materials.Sput_ST_Metal_Dark} />
              <mesh geometry={nodes.pCube131_Sput_ST_Metal_Dark_02_0.geometry} material={materials.Sput_ST_Metal_Dark_02} />
              <mesh geometry={nodes.pCube132_Sput_ST_Metal_light_0.geometry} material={materials.Sput_ST_Metal_light} />
              <mesh geometry={nodes.polySurface15_Sput_ST_Metal_Dark_0.geometry} material={materials.Sput_ST_Metal_Dark} />
              <mesh geometry={nodes.pCube130_Sput_ST_Metal_light_0.geometry} material={materials.Sput_ST_Metal_light} />
              <mesh geometry={nodes.pCylinder88_Sput_ST_Metal_light_0.geometry} material={materials.Sput_ST_Metal_light} />
              <mesh geometry={nodes.pCylinder89_Sput_ST_Metal_light_0.geometry} material={materials.Sput_ST_Metal_light} />
              <mesh geometry={nodes.pCube133_Sput_ST_Metal_light_0.geometry} material={materials.Sput_ST_Metal_light} />
              <mesh geometry={nodes.pCylinder84_Sput_ST_Metal_Dark_0.geometry} material={materials.Sput_ST_Metal_Dark} />
              <mesh geometry={nodes.pCylinder84_Sput_ST_Metal_Gold_0.geometry} material={materials.Sput_ST_Metal_Gold} />
              <mesh geometry={nodes.pCube124_Sput_ST_Metal_light_0.geometry} material={materials.Sput_ST_Metal_light} />
              <mesh geometry={nodes.pCube123_Sput_ST_Metal_Dark_0.geometry} material={materials.Sput_ST_Metal_Dark} />
              <mesh geometry={nodes.pCylinder86_Sput_ST_Metal_light_0.geometry} material={materials.Sput_ST_Metal_light} />
              <mesh geometry={nodes.pCylinder87_Sput_ST_Metal_light_0.geometry} material={materials.Sput_ST_Metal_light} />
              <mesh geometry={nodes.pCube129_Sput_ST_Metal_Dark_02_0.geometry} material={materials.Sput_ST_Metal_Dark_02} />
              <mesh geometry={nodes.pCube90_Sput_ST_Metal_light_0.geometry} material={materials.Sput_ST_Metal_light} />
              <mesh geometry={nodes.pCube122_Sput_ST_Metal_Dark_0.geometry} material={materials.Sput_ST_Metal_Dark} />
              <mesh geometry={nodes.pCube127_Sput_ST_Metal_light_0_1.geometry} material={materials.Sput_ST_Metal_light} />
              <mesh geometry={nodes.polySurface14_Sput_ST_Metal_Dark_0_1.geometry} material={materials.Sput_ST_Metal_Dark} />
              <mesh geometry={nodes.pCube131_Sput_ST_Metal_Dark_02_0_1.geometry} material={materials.Sput_ST_Metal_Dark_02} />
              <mesh geometry={nodes.pCube132_Sput_ST_Metal_light_0_1.geometry} material={materials.Sput_ST_Metal_light} />
              <mesh geometry={nodes.polySurface16_Sput_ST_Metal_Dark_02_0.geometry} material={materials.Sput_ST_Metal_Dark_02} />
              <mesh geometry={nodes.polySurface15_Sput_ST_Metal_Dark_0_1.geometry} material={materials.Sput_ST_Metal_Dark} />
              <mesh geometry={nodes.pCube130_Sput_ST_Metal_light_0_1.geometry} material={materials.Sput_ST_Metal_light} />
              <mesh geometry={nodes.pCylinder88_Sput_ST_Metal_light_0_1.geometry} material={materials.Sput_ST_Metal_light} />
              <mesh geometry={nodes.pCylinder89_Sput_ST_Metal_light_0_1.geometry} material={materials.Sput_ST_Metal_light} />
              <mesh geometry={nodes.pCube133_Sput_ST_Metal_light_0_1.geometry} material={materials.Sput_ST_Metal_light} />
              <mesh geometry={nodes.polySurface13_Sput_ST_Metal_Dark_02_0.geometry} material={materials.Sput_ST_Metal_Dark_02} />
              <mesh geometry={nodes.pCylinder84_Sput_ST_Metal_Dark_0_1.geometry} material={materials.Sput_ST_Metal_Dark} />
              <mesh geometry={nodes.pCylinder84_Sput_ST_Metal_Gold_0_1.geometry} material={materials.Sput_ST_Metal_Gold} />
              <mesh geometry={nodes.pCube124_Sput_ST_Metal_light_0_1.geometry} material={materials.Sput_ST_Metal_light} />
              <mesh geometry={nodes.pCylinder86_Sput_ST_Metal_light_0_1.geometry} material={materials.Sput_ST_Metal_light} />
              <mesh geometry={nodes.pCylinder87_Sput_ST_Metal_light_0_1.geometry} material={materials.Sput_ST_Metal_light} />
              <mesh geometry={nodes.pCube129_Sput_ST_Metal_Dark_02_0_1.geometry} material={materials.Sput_ST_Metal_Dark_02} />
              <mesh geometry={nodes.pCube90_Sput_ST_Metal_light_0_1.geometry} material={materials.Sput_ST_Metal_light} />
              <mesh geometry={nodes.pCube154_Indicator_Orange_01_0.geometry} material={materials.Indicator_Orange_01} />
              <mesh geometry={nodes.pCube155_Indicator_Orange_01_0.geometry} material={materials.Indicator_Orange_01} />
              <mesh geometry={nodes.polySurface6_Sput_ST_Batary_0.geometry} material={materials.Sput_ST_Batary} />
              <mesh geometry={nodes.polySurface6_Sput_ST_Metal_Gold_0.geometry} material={materials.Sput_ST_Metal_Gold} />
              <mesh geometry={nodes.polySurface11_Sput_ST_Metal_Dark_0.geometry} material={materials.Sput_ST_Metal_Dark} />
              <mesh geometry={nodes.polySurface18_Sput_ST_Metal_Dark_02_0.geometry} material={materials.Sput_ST_Metal_Dark_02} />
              <mesh geometry={nodes.polySurface17_Sput_ST_Metal_Dark_02_0.geometry} material={materials.Sput_ST_Metal_Dark_02} />
              <mesh geometry={nodes.polySurface11_Sput_ST_Metal_Dark_0_1.geometry} material={materials.Sput_ST_Metal_Dark} />
              <mesh geometry={nodes.polySurface21_Sput_ST_Batary_0.geometry} material={materials.Sput_ST_Batary} />
              <mesh geometry={nodes.polySurface21_Sput_ST_Metal_Gold_0.geometry} material={materials.Sput_ST_Metal_Gold} />
              <mesh geometry={nodes.polySurface11_Sput_ST_Metal_Dark_0_2.geometry} material={materials.Sput_ST_Metal_Dark} />
              <mesh geometry={nodes.polySurface22_Sput_ST_Batary_0.geometry} material={materials.Sput_ST_Batary} />
              <mesh geometry={nodes.polySurface22_Sput_ST_Metal_Gold_0.geometry} material={materials.Sput_ST_Metal_Gold} />
              <mesh geometry={nodes.pCube127_Sput_ST_Metal_light_0_2.geometry} material={materials.Sput_ST_Metal_light} />
              <mesh geometry={nodes.polySurface14_Sput_ST_Metal_Dark_0_2.geometry} material={materials.Sput_ST_Metal_Dark} />
              <mesh geometry={nodes.polySurface12_Sput_ST_Metal_Dark_0_1.geometry} material={materials.Sput_ST_Metal_Dark} />
              <mesh geometry={nodes.pCube131_Sput_ST_Metal_Dark_02_0_2.geometry} material={materials.Sput_ST_Metal_Dark_02} />
              <mesh geometry={nodes.pCube132_Sput_ST_Metal_light_0_2.geometry} material={materials.Sput_ST_Metal_light} />
              <mesh geometry={nodes.polySurface15_Sput_ST_Metal_Dark_0_2.geometry} material={materials.Sput_ST_Metal_Dark} />
              <mesh geometry={nodes.pCube130_Sput_ST_Metal_light_0_2.geometry} material={materials.Sput_ST_Metal_light} />
              <mesh geometry={nodes.pCylinder88_Sput_ST_Metal_light_0_2.geometry} material={materials.Sput_ST_Metal_light} />
              <mesh geometry={nodes.pCylinder89_Sput_ST_Metal_light_0_2.geometry} material={materials.Sput_ST_Metal_light} />
              <mesh geometry={nodes.pCube133_Sput_ST_Metal_light_0_2.geometry} material={materials.Sput_ST_Metal_light} />
              <mesh geometry={nodes.pCylinder84_Sput_ST_Metal_Dark_0_2.geometry} material={materials.Sput_ST_Metal_Dark} />
              <mesh geometry={nodes.pCylinder84_Sput_ST_Metal_Gold_0_2.geometry} material={materials.Sput_ST_Metal_Gold} />
              <mesh geometry={nodes.pCube124_Sput_ST_Metal_light_0_2.geometry} material={materials.Sput_ST_Metal_light} />
              <mesh geometry={nodes.pCube123_Sput_ST_Metal_Dark_0_1.geometry} material={materials.Sput_ST_Metal_Dark} />
              <mesh geometry={nodes.pCylinder86_Sput_ST_Metal_light_0_2.geometry} material={materials.Sput_ST_Metal_light} />
              <mesh geometry={nodes.pCylinder87_Sput_ST_Metal_light_0_2.geometry} material={materials.Sput_ST_Metal_light} />
              <mesh geometry={nodes.pCube129_Sput_ST_Metal_Dark_02_0_2.geometry} material={materials.Sput_ST_Metal_Dark_02} />
              <mesh geometry={nodes.pCube90_Sput_ST_Metal_light_0_2.geometry} material={materials.Sput_ST_Metal_light} />
              <mesh geometry={nodes.pCube122_Sput_ST_Metal_Dark_0_1.geometry} material={materials.Sput_ST_Metal_Dark} />
              <mesh geometry={nodes.pCube134_Sput_ST_Metal_Dark_0.geometry} material={materials.Sput_ST_Metal_Dark} />
              <mesh geometry={nodes.pCube135_Sput_ST_Metal_Dark_0.geometry} material={materials.Sput_ST_Metal_Dark} />
              <mesh geometry={nodes.pCube94_Sput_ST_Metal_0.geometry} material={materials.Sput_ST_Metal} />
              <mesh geometry={nodes.Solar_Antenna_Left_Solar_Battery_group22_polySurface12_Sput_ST_Metal_Dark_0.geometry} material={materials.Sput_ST_Metal_Dark} />
              <mesh geometry={nodes.polySurface19_Sput_ST_Metal_Dark_02_0.geometry} material={materials.Sput_ST_Metal_Dark_02} />
              <mesh geometry={nodes.polySurface20_Sput_ST_Metal_Dark_02_0.geometry} material={materials.Sput_ST_Metal_Dark_02} />
            </group>
            <mesh geometry={nodes.pCube97_Sput_ST_Metal_Dark_0.geometry} material={materials.Sput_ST_Metal_Dark} />
            <mesh geometry={nodes.pCylinder34_Sput_ST_Metal_Dark_0.geometry} material={materials.Sput_ST_Metal_Dark} />
            <mesh geometry={nodes.pCylinder91_Sput_ST_Metal_light_0.geometry} material={materials.Sput_ST_Metal_light} />
            <mesh geometry={nodes.pCylinder92_Sput_ST_Metal_Dark_0.geometry} material={materials.Sput_ST_Metal_Dark} />
            <mesh geometry={nodes.pCylinder117_Sput_ST_Metal_Dark_02_0.geometry} material={materials.Sput_ST_Metal_Dark_02} />
            <mesh geometry={nodes.pCube137_Sput_ST_Metal_Dark_02_0.geometry} material={materials.Sput_ST_Metal_Dark_02} />
            <mesh geometry={nodes.pCube136_Sput_ST_Metal_Dark_02_0.geometry} material={materials.Sput_ST_Metal_Dark_02} />
            <group position={[5.15, -2.33, 0]} rotation={[0, 0, Math.PI / 4]}>
              <mesh geometry={nodes.pCube127_Sput_ST_Metal_light_0_3.geometry} material={materials.Sput_ST_Metal_light} />
              <mesh geometry={nodes.polySurface14_Sput_ST_Metal_Dark_0_3.geometry} material={materials.Sput_ST_Metal_Dark} />
              <mesh geometry={nodes.polySurface12_Sput_ST_Metal_Dark_0_2.geometry} material={materials.Sput_ST_Metal_Dark} />
              <mesh geometry={nodes.pCube131_Sput_ST_Metal_Dark_02_0_3.geometry} material={materials.Sput_ST_Metal_Dark_02} />
              <mesh geometry={nodes.pCube132_Sput_ST_Metal_light_0_3.geometry} material={materials.Sput_ST_Metal_light} />
              <mesh geometry={nodes.polySurface15_Sput_ST_Metal_Dark_0_3.geometry} material={materials.Sput_ST_Metal_Dark} />
              <mesh geometry={nodes.pCube130_Sput_ST_Metal_light_0_3.geometry} material={materials.Sput_ST_Metal_light} />
              <mesh geometry={nodes.pCylinder88_Sput_ST_Metal_light_0_3.geometry} material={materials.Sput_ST_Metal_light} />
              <mesh geometry={nodes.pCylinder89_Sput_ST_Metal_light_0_3.geometry} material={materials.Sput_ST_Metal_light} />
              <mesh geometry={nodes.pCube133_Sput_ST_Metal_light_0_3.geometry} material={materials.Sput_ST_Metal_light} />
              <mesh geometry={nodes.pCylinder84_Sput_ST_Metal_Dark_0_3.geometry} material={materials.Sput_ST_Metal_Dark} />
              <mesh geometry={nodes.pCylinder84_Sput_ST_Metal_Gold_0_3.geometry} material={materials.Sput_ST_Metal_Gold} />
              <mesh geometry={nodes.pCube124_Sput_ST_Metal_light_0_3.geometry} material={materials.Sput_ST_Metal_light} />
              <mesh geometry={nodes.pCube123_Sput_ST_Metal_Dark_0_2.geometry} material={materials.Sput_ST_Metal_Dark} />
              <mesh geometry={nodes.pCylinder86_Sput_ST_Metal_light_0_3.geometry} material={materials.Sput_ST_Metal_light} />
              <mesh geometry={nodes.pCylinder87_Sput_ST_Metal_light_0_3.geometry} material={materials.Sput_ST_Metal_light} />
              <mesh geometry={nodes.pCube129_Sput_ST_Metal_Dark_02_0_3.geometry} material={materials.Sput_ST_Metal_Dark_02} />
              <mesh geometry={nodes.pCube90_Sput_ST_Metal_light_0_3.geometry} material={materials.Sput_ST_Metal_light} />
              <mesh geometry={nodes.pCube122_Sput_ST_Metal_Dark_0_2.geometry} material={materials.Sput_ST_Metal_Dark} />
              <mesh geometry={nodes.pCube127_Sput_ST_Metal_light_0_4.geometry} material={materials.Sput_ST_Metal_light} />
              <mesh geometry={nodes.polySurface14_Sput_ST_Metal_Dark_0_4.geometry} material={materials.Sput_ST_Metal_Dark} />
              <mesh geometry={nodes.pCube131_Sput_ST_Metal_Dark_02_0_4.geometry} material={materials.Sput_ST_Metal_Dark_02} />
              <mesh geometry={nodes.pCube132_Sput_ST_Metal_light_0_4.geometry} material={materials.Sput_ST_Metal_light} />
              <mesh geometry={nodes.polySurface16_Sput_ST_Metal_Dark_02_0_1.geometry} material={materials.Sput_ST_Metal_Dark_02} position={[-2.04, 0, 0]} scale={[1.3, 1, 1]} />
              <mesh geometry={nodes.polySurface15_Sput_ST_Metal_Dark_0_4.geometry} material={materials.Sput_ST_Metal_Dark} />
              <mesh geometry={nodes.pCube130_Sput_ST_Metal_light_0_4.geometry} material={materials.Sput_ST_Metal_light} />
              <mesh geometry={nodes.pCylinder88_Sput_ST_Metal_light_0_4.geometry} material={materials.Sput_ST_Metal_light} />
              <mesh geometry={nodes.pCylinder89_Sput_ST_Metal_light_0_4.geometry} material={materials.Sput_ST_Metal_light} />
              <mesh geometry={nodes.pCube133_Sput_ST_Metal_light_0_4.geometry} material={materials.Sput_ST_Metal_light} />
              <mesh geometry={nodes.polySurface13_Sput_ST_Metal_Dark_02_0_1.geometry} material={materials.Sput_ST_Metal_Dark_02} position={[-1.2, 0, 0]} scale={[1.3, 1, 1]} />
              <mesh geometry={nodes.pCylinder84_Sput_ST_Metal_Dark_0_4.geometry} material={materials.Sput_ST_Metal_Dark} />
              <mesh geometry={nodes.pCylinder84_Sput_ST_Metal_Gold_0_4.geometry} material={materials.Sput_ST_Metal_Gold} />
              <mesh geometry={nodes.pCube124_Sput_ST_Metal_light_0_4.geometry} material={materials.Sput_ST_Metal_light} />
              <mesh geometry={nodes.pCylinder86_Sput_ST_Metal_light_0_4.geometry} material={materials.Sput_ST_Metal_light} />
              <mesh geometry={nodes.pCylinder87_Sput_ST_Metal_light_0_4.geometry} material={materials.Sput_ST_Metal_light} />
              <mesh geometry={nodes.pCube129_Sput_ST_Metal_Dark_02_0_4.geometry} material={materials.Sput_ST_Metal_Dark_02} />
              <mesh geometry={nodes.pCube90_Sput_ST_Metal_light_0_4.geometry} material={materials.Sput_ST_Metal_light} />
              <mesh geometry={nodes.pCube154_Indicator_Orange_01_0_1.geometry} material={materials.Indicator_Orange_01} />
              <mesh geometry={nodes.pCube155_Indicator_Orange_01_0_1.geometry} material={materials.Indicator_Orange_01} />
              <mesh geometry={nodes.polySurface6_Sput_ST_Batary_0_1.geometry} material={materials.Sput_ST_Batary} />
              <mesh geometry={nodes.polySurface6_Sput_ST_Metal_Gold_0_1.geometry} material={materials.Sput_ST_Metal_Gold} />
              <mesh geometry={nodes.polySurface11_Sput_ST_Metal_Dark_0_3.geometry} material={materials.Sput_ST_Metal_Dark} />
              <mesh geometry={nodes.polySurface18_Sput_ST_Metal_Dark_02_0_1.geometry} material={materials.Sput_ST_Metal_Dark_02} position={[-2.04, 0, -4.47]} scale={[1.3, 1, 1]} />
              <mesh geometry={nodes.polySurface17_Sput_ST_Metal_Dark_02_0_1.geometry} material={materials.Sput_ST_Metal_Dark_02} position={[-1.2, 0, -4.47]} scale={[1.3, 1, 1]} />
              <group position={[0, 0, -4.51]}>
                <mesh geometry={nodes.polySurface21_Sput_ST_Batary_0_1.geometry} material={materials.Sput_ST_Batary} />
                <mesh geometry={nodes.polySurface21_Sput_ST_Metal_Gold_0_1.geometry} material={materials.Sput_ST_Metal_Gold} />
              </group>
              <mesh geometry={nodes.polySurface11_Sput_ST_Metal_Dark_0_4.geometry} material={materials.Sput_ST_Metal_Dark} />
              <group position={[0, 0, -9.01]}>
                <mesh geometry={nodes.polySurface22_Sput_ST_Batary_0_1.geometry} material={materials.Sput_ST_Batary} />
                <mesh geometry={nodes.polySurface22_Sput_ST_Metal_Gold_0_1.geometry} material={materials.Sput_ST_Metal_Gold} />
              </group>
              <mesh geometry={nodes.polySurface11_Sput_ST_Metal_Dark_0_5.geometry} material={materials.Sput_ST_Metal_Dark} />
              <mesh geometry={nodes.pCube127_Sput_ST_Metal_light_0_5.geometry} material={materials.Sput_ST_Metal_light} />
              <mesh geometry={nodes.polySurface14_Sput_ST_Metal_Dark_0_5.geometry} material={materials.Sput_ST_Metal_Dark} />
              <mesh geometry={nodes.polySurface12_Sput_ST_Metal_Dark_0_3.geometry} material={materials.Sput_ST_Metal_Dark} />
              <mesh geometry={nodes.pCube131_Sput_ST_Metal_Dark_02_0_5.geometry} material={materials.Sput_ST_Metal_Dark_02} />
              <mesh geometry={nodes.pCube132_Sput_ST_Metal_light_0_5.geometry} material={materials.Sput_ST_Metal_light} />
              <mesh geometry={nodes.polySurface15_Sput_ST_Metal_Dark_0_5.geometry} material={materials.Sput_ST_Metal_Dark} />
              <mesh geometry={nodes.pCube130_Sput_ST_Metal_light_0_5.geometry} material={materials.Sput_ST_Metal_light} />
              <mesh geometry={nodes.pCylinder88_Sput_ST_Metal_light_0_5.geometry} material={materials.Sput_ST_Metal_light} />
              <mesh geometry={nodes.pCylinder89_Sput_ST_Metal_light_0_5.geometry} material={materials.Sput_ST_Metal_light} />
              <mesh geometry={nodes.pCube133_Sput_ST_Metal_light_0_5.geometry} material={materials.Sput_ST_Metal_light} />
              <mesh geometry={nodes.pCylinder84_Sput_ST_Metal_Dark_0_5.geometry} material={materials.Sput_ST_Metal_Dark} />
              <mesh geometry={nodes.pCylinder84_Sput_ST_Metal_Gold_0_5.geometry} material={materials.Sput_ST_Metal_Gold} />
              <mesh geometry={nodes.pCube124_Sput_ST_Metal_light_0_5.geometry} material={materials.Sput_ST_Metal_light} />
              <mesh geometry={nodes.pCube123_Sput_ST_Metal_Dark_0_3.geometry} material={materials.Sput_ST_Metal_Dark} />
              <mesh geometry={nodes.pCylinder86_Sput_ST_Metal_light_0_5.geometry} material={materials.Sput_ST_Metal_light} />
              <mesh geometry={nodes.pCylinder87_Sput_ST_Metal_light_0_5.geometry} material={materials.Sput_ST_Metal_light} />
              <mesh geometry={nodes.pCube129_Sput_ST_Metal_Dark_02_0_5.geometry} material={materials.Sput_ST_Metal_Dark_02} />
              <mesh geometry={nodes.pCube90_Sput_ST_Metal_light_0_5.geometry} material={materials.Sput_ST_Metal_light} />
              <mesh geometry={nodes.pCube122_Sput_ST_Metal_Dark_0_3.geometry} material={materials.Sput_ST_Metal_Dark} />
              <mesh geometry={nodes.pCube134_Sput_ST_Metal_Dark_0_1.geometry} material={materials.Sput_ST_Metal_Dark} />
              <mesh geometry={nodes.pCube135_Sput_ST_Metal_Dark_0_1.geometry} material={materials.Sput_ST_Metal_Dark} />
              <mesh geometry={nodes.pCube94_Sput_ST_Metal_0_1.geometry} material={materials.Sput_ST_Metal} />
              <mesh geometry={nodes.Solar_Antenna_Left_Solar_Battery_group22_polySurface12_Sput_ST_Metal_Dark_0_1.geometry} material={materials.Sput_ST_Metal_Dark} />
              <mesh geometry={nodes.polySurface19_Sput_ST_Metal_Dark_02_0_1.geometry} material={materials.Sput_ST_Metal_Dark_02} position={[-2.04, 0, -8.98]} scale={[1.3, 1, 1]} />
              <mesh geometry={nodes.polySurface20_Sput_ST_Metal_Dark_02_0_1.geometry} material={materials.Sput_ST_Metal_Dark_02} position={[-1.2, 0, -8.98]} scale={[1.3, 1, 1]} />
            </group>
            <mesh geometry={nodes.pCube97_Sput_ST_Metal_Dark_0_1.geometry} material={materials.Sput_ST_Metal_Dark} />
            <mesh geometry={nodes.pCylinder34_Sput_ST_Metal_Dark_0_1.geometry} material={materials.Sput_ST_Metal_Dark} />
            <mesh geometry={nodes.pCylinder91_Sput_ST_Metal_light_0_1.geometry} material={materials.Sput_ST_Metal_light} />
            <mesh geometry={nodes.pCylinder92_Sput_ST_Metal_Dark_0_1.geometry} material={materials.Sput_ST_Metal_Dark} />
            <mesh geometry={nodes.pCylinder117_Sput_ST_Metal_Dark_02_0_1.geometry} material={materials.Sput_ST_Metal_Dark_02} />
            <mesh geometry={nodes.pCube137_Sput_ST_Metal_Dark_02_0_1.geometry} material={materials.Sput_ST_Metal_Dark_02} />
            <mesh geometry={nodes.pCube136_Sput_ST_Metal_Dark_02_0_1.geometry} material={materials.Sput_ST_Metal_Dark_02} />
            <mesh geometry={nodes.pCylinder196_Sput_Trubka_Or_0.geometry} material={materials.Sput_Trubka_Or} />
            <mesh geometry={nodes.pCube101_Sput_ST_Metal_Dark_0_1.geometry} material={materials.Sput_ST_Metal_Dark} />
            <mesh geometry={nodes.pCube151_Indicator_Orange_01_0.geometry} material={materials.Indicator_Orange_01} />
            <mesh geometry={nodes.pCube101_Sput_ST_Metal_Dark_0_2.geometry} material={materials.Sput_ST_Metal_Dark} />
            <mesh geometry={nodes.pCube151_Indicator_Orange_Off_0.geometry} material={materials.Indicator_Orange_Off} />
            <mesh geometry={nodes.pCube101_Sput_ST_Metal_Dark_0_3.geometry} material={materials.Sput_ST_Metal_Dark} />
            <mesh geometry={nodes.pCube151_Indicator_Orange_01_0_1.geometry} material={materials.Indicator_Orange_01} />
            <mesh geometry={nodes.pCube100_Sput_ST_Metal_Dark_0.geometry} material={materials.Sput_ST_Metal_Dark} />
            <mesh geometry={nodes.pCube152_Indicator_Orange_01_0.geometry} material={materials.Indicator_Orange_01} />
            <mesh geometry={nodes.pCube151_Indicator_Orange_01_0_2.geometry} material={materials.Indicator_Orange_01} />
            <mesh geometry={nodes.pCylinder193_Sput_ST_Metal_0.geometry} material={materials.Sput_ST_Metal} />
            <mesh geometry={nodes.pCylinder193_Sput_Glass_01_0.geometry} material={materials.Sput_Glass_01} />
            <mesh geometry={nodes.pCylinder193_Robot_Glass_0.geometry} material={materials.Robot_Glass} />
            <mesh geometry={nodes.pCylinder190_Sput_ST_Metal_Gold_0.geometry} material={materials.Sput_ST_Metal_Gold} />
            <mesh geometry={nodes.pCylinder189_Sput_ST_Metal_Gold_0.geometry} material={materials.Sput_ST_Metal_Gold} />
            <mesh geometry={nodes.pCylinder191_Sput_ST_Metal_Gold_0.geometry} material={materials.Sput_ST_Metal_Gold} />
            <mesh geometry={nodes.pCylinder190_Sput_ST_Metal_Gold_0_1.geometry} material={materials.Sput_ST_Metal_Gold} />
            <mesh geometry={nodes.pCylinder189_Sput_ST_Metal_Gold_0_1.geometry} material={materials.Sput_ST_Metal_Gold} />
            <mesh geometry={nodes.pCylinder191_Sput_ST_Metal_Gold_0_1.geometry} material={materials.Sput_ST_Metal_Gold} />
            <mesh geometry={nodes.pCylinder190_Sput_ST_Metal_Gold_0_2.geometry} material={materials.Sput_ST_Metal_Gold} />
            <mesh geometry={nodes.pCylinder189_Sput_ST_Metal_Gold_0_2.geometry} material={materials.Sput_ST_Metal_Gold} />
            <mesh geometry={nodes.pCylinder191_Sput_ST_Metal_Gold_0_2.geometry} material={materials.Sput_ST_Metal_Gold} />
            <mesh geometry={nodes.pCylinder190_Sput_ST_Metal_Gold_0_3.geometry} material={materials.Sput_ST_Metal_Gold} />
            <mesh geometry={nodes.pCylinder189_Sput_ST_Metal_Gold_0_3.geometry} material={materials.Sput_ST_Metal_Gold} />
            <mesh geometry={nodes.pCylinder191_Sput_ST_Metal_Gold_0_3.geometry} material={materials.Sput_ST_Metal_Gold} />
            <mesh geometry={nodes.pCube101_Sput_ST_Metal_Dark_0_4.geometry} material={materials.Sput_ST_Metal_Dark} />
            <mesh geometry={nodes.pCube151_Indicator_Orange_01_0_3.geometry} material={materials.Indicator_Orange_01} />
            <mesh geometry={nodes.pCylinder183_Sput_ST_Metal_Dark_0.geometry} material={materials.Sput_ST_Metal_Dark} />
            <mesh geometry={nodes.pCylinder182_Sput_ST_Metal_Dark_0.geometry} material={materials.Sput_ST_Metal_Dark} />
            <mesh geometry={nodes.pCylinder181_Sput_ST_Metal_Dark_0.geometry} material={materials.Sput_ST_Metal_Dark} />
            <mesh geometry={nodes.pCylinder180_Sput_ST_Metal_Dark_0.geometry} material={materials.Sput_ST_Metal_Dark} />
            <mesh geometry={nodes.pCylinder179_Sput_ST_Metal_Dark_0.geometry} material={materials.Sput_ST_Metal_Dark} />
            <mesh geometry={nodes.pCylinder118_Sput_Trubka_Or_0.geometry} material={materials.Sput_Trubka_Or} />
            <mesh geometry={nodes.pCylinder72_Sput_ST_Metal_Dark_0.geometry} material={materials.Sput_ST_Metal_Dark} />
            <mesh geometry={nodes.pCube107_Sput_Red_ST_0.geometry} material={materials.Sput_Red_ST} />
            <mesh geometry={nodes.pCube105_Sput_Red_ST_0.geometry} material={materials.Sput_Red_ST} />
            <mesh geometry={nodes.pCube106_Sput_Red_ST_0.geometry} material={materials.Sput_Red_ST} />
            <mesh geometry={nodes.pCylinder131_Sput_ST_Metal_Dark_0.geometry} material={materials.Sput_ST_Metal_Dark} />
            <mesh geometry={nodes.pCube147_Sput_ST_Metal_Dark_0.geometry} material={materials.Sput_ST_Metal_Dark} />
            <mesh geometry={nodes.pCylinder132_Sput_ST_Metal_light_0.geometry} material={materials.Sput_ST_Metal_light} />
            <mesh geometry={nodes.pCylinder134_Sput_ST_Metal_light_0.geometry} material={materials.Sput_ST_Metal_light} />
            <mesh geometry={nodes.pCylinder137_Sput_ST_Metal_Dark_0.geometry} material={materials.Sput_ST_Metal_Dark} />
            <mesh geometry={nodes.pCylinder135_Sput_ST_Metal_light_0.geometry} material={materials.Sput_ST_Metal_light} />
            <mesh geometry={nodes.pCylinder136_Sput_ST_Metal_light_0.geometry} material={materials.Sput_ST_Metal_light} />
            <mesh geometry={nodes.pCylinder138_Sput_ST_Metal_light_0.geometry} material={materials.Sput_ST_Metal_light} />
            <mesh geometry={nodes.pCylinder133_Sput_ST_Metal_light_0.geometry} material={materials.Sput_ST_Metal_light} />
            <mesh geometry={nodes.pCylinder140_Sput_ST_Metal_light_0.geometry} material={materials.Sput_ST_Metal_light} />
            <mesh geometry={nodes.pCylinder143_Sput_ST_Metal_light_0.geometry} material={materials.Sput_ST_Metal_light} />
            <mesh geometry={nodes.pCylinder142_Sput_ST_Metal_light_0.geometry} material={materials.Sput_ST_Metal_light} />
            <mesh geometry={nodes.pCylinder139_Sput_ST_Metal_light_0.geometry} material={materials.Sput_ST_Metal_light} />
            <mesh geometry={nodes.pCylinder141_Sput_ST_Metal_light_0.geometry} material={materials.Sput_ST_Metal_light} />
            <mesh geometry={nodes.pCylinder131_Sput_ST_Metal_Dark_0_1.geometry} material={materials.Sput_ST_Metal_Dark} />
            <mesh geometry={nodes.pCube147_Sput_ST_Metal_Dark_0_1.geometry} material={materials.Sput_ST_Metal_Dark} />
            <mesh geometry={nodes.pCylinder132_Sput_ST_Metal_light_0_1.geometry} material={materials.Sput_ST_Metal_light} />
            <mesh geometry={nodes.pCylinder134_Sput_ST_Metal_light_0_1.geometry} material={materials.Sput_ST_Metal_light} />
            <mesh geometry={nodes.pCylinder137_Sput_ST_Metal_Dark_0_1.geometry} material={materials.Sput_ST_Metal_Dark} />
            <mesh geometry={nodes.pCylinder135_Sput_ST_Metal_light_0_1.geometry} material={materials.Sput_ST_Metal_light} />
            <mesh geometry={nodes.pCylinder136_Sput_ST_Metal_light_0_1.geometry} material={materials.Sput_ST_Metal_light} />
            <mesh geometry={nodes.pCylinder138_Sput_ST_Metal_light_0_1.geometry} material={materials.Sput_ST_Metal_light} />
            <mesh geometry={nodes.pCylinder133_Sput_ST_Metal_light_0_1.geometry} material={materials.Sput_ST_Metal_light} />
            <mesh geometry={nodes.pCylinder140_Sput_ST_Metal_light_0_1.geometry} material={materials.Sput_ST_Metal_light} />
            <mesh geometry={nodes.pCylinder143_Sput_ST_Metal_light_0_1.geometry} material={materials.Sput_ST_Metal_light} />
            <mesh geometry={nodes.pCylinder142_Sput_ST_Metal_light_0_1.geometry} material={materials.Sput_ST_Metal_light} />
            <mesh geometry={nodes.pCylinder139_Sput_ST_Metal_light_0_1.geometry} material={materials.Sput_ST_Metal_light} />
            <mesh geometry={nodes.pCylinder141_Sput_ST_Metal_light_0_1.geometry} material={materials.Sput_ST_Metal_light} />
            <mesh geometry={nodes.pCube85_Sput_ST_Metal_Dark_0.geometry} material={materials.Sput_ST_Metal_Dark} />
            <mesh geometry={nodes.pCube148_Sput_ST_Metal_light_0.geometry} material={materials.Sput_ST_Metal_light} />
            <mesh geometry={nodes.pCylinder147_Sput_Gold_Back_0.geometry} material={materials.Sput_Gold_Back} />
            <mesh geometry={nodes.pCylinder147_Sput_ST_Metal_Dark_02_0.geometry} material={materials.Sput_ST_Metal_Dark_02} />
            <mesh geometry={nodes.pCylinder144_Sput_ST_Metal_Dark_0.geometry} material={materials.Sput_ST_Metal_Dark} />
            <mesh geometry={nodes.pCylinder169_Sput_ST_Metal_light_0.geometry} material={materials.Sput_ST_Metal_light} />
            <mesh geometry={nodes.pCylinder161_Sput_ST_Metal_light_0.geometry} material={materials.Sput_ST_Metal_light} />
            <mesh geometry={nodes.pCylinder158_Sput_ST_Metal_light_0.geometry} material={materials.Sput_ST_Metal_light} />
            <mesh geometry={nodes.pCylinder166_Sput_ST_Metal_Dark_02_0.geometry} material={materials.Sput_ST_Metal_Dark_02} />
            <mesh geometry={nodes.pCylinder150_Sput_ST_Metal_light_0.geometry} material={materials.Sput_ST_Metal_light} />
            <mesh geometry={nodes.pCylinder152_Sput_ST_Metal_Dark_0.geometry} material={materials.Sput_ST_Metal_Dark} />
            <mesh geometry={nodes.pCylinder160_Sput_ST_Metal_light_0.geometry} material={materials.Sput_ST_Metal_light} />
            <mesh geometry={nodes.pCylinder162_Sput_ST_Metal_light_0.geometry} material={materials.Sput_ST_Metal_light} />
            <mesh geometry={nodes.pCylinder157_Sput_ST_Metal_light_0.geometry} material={materials.Sput_ST_Metal_light} />
            <mesh geometry={nodes.pCylinder156_Sput_ST_Metal_Dark_02_0.geometry} material={materials.Sput_ST_Metal_Dark_02} />
            <mesh geometry={nodes.pCylinder164_Sput_ST_Metal_light_0.geometry} material={materials.Sput_ST_Metal_light} />
            <mesh geometry={nodes.pCylinder163_Sput_ST_Metal_light_0.geometry} material={materials.Sput_ST_Metal_light} />
            <mesh geometry={nodes.pCylinder178_Sput_ST_Metal_Dark_02_0.geometry} material={materials.Sput_ST_Metal_Dark_02} />
            <mesh geometry={nodes.pCylinder30_Sput_Gold_Back_0.geometry} material={materials.Sput_Gold_Back} />
            <mesh geometry={nodes.pCylinder155_Sput_ST_Metal_light_0.geometry} material={materials.Sput_ST_Metal_light} />
            <mesh geometry={nodes.pCylinder148_Sput_ST_Metal_Dark_0.geometry} material={materials.Sput_ST_Metal_Dark} />
            <mesh geometry={nodes.pCylinder168_Sput_ST_Metal_light_0.geometry} material={materials.Sput_ST_Metal_light} />
            <mesh geometry={nodes.pCylinder167_Sput_ST_Metal_Dark_02_0.geometry} material={materials.Sput_ST_Metal_Dark_02} />
            <mesh geometry={nodes.pCube149_Sput_ST_Metal_Dark_0.geometry} material={materials.Sput_ST_Metal_Dark} />
            <mesh geometry={nodes.pCylinder159_Sput_ST_Metal_light_0.geometry} material={materials.Sput_ST_Metal_light} />
            <mesh geometry={nodes.pCylinder153_Sput_ST_Metal_light_0.geometry} material={materials.Sput_ST_Metal_light} />
            <mesh geometry={nodes.pCylinder154_Sput_ST_Metal_light_0.geometry} material={materials.Sput_ST_Metal_light} />
            <mesh geometry={nodes.pCylinder165_Sput_ST_Metal_Dark_0.geometry} material={materials.Sput_ST_Metal_Dark} />
            <mesh geometry={nodes.pCylinder173_Sput_ST_Metal_Dark_02_0.geometry} material={materials.Sput_ST_Metal_Dark_02} />
            <mesh geometry={nodes.pCylinder172_Sput_ST_Metal_Dark_02_0.geometry} material={materials.Sput_ST_Metal_Dark_02} />
            <mesh geometry={nodes.pCylinder171_Sput_ST_Metal_Dark_0.geometry} material={materials.Sput_ST_Metal_Dark} />
            <mesh geometry={nodes.pCylinder170_Sput_ST_Metal_Dark_0.geometry} material={materials.Sput_ST_Metal_Dark} />
            <mesh geometry={nodes.pCylinder174_Sput_ST_Metal_light_0.geometry} material={materials.Sput_ST_Metal_light} />
            <mesh geometry={nodes.pCylinder175_Sput_ST_Metal_light_0.geometry} material={materials.Sput_ST_Metal_light} />
            <mesh geometry={nodes.pCylinder177_Sput_ST_Metal_light_0.geometry} material={materials.Sput_ST_Metal_light} />
            <mesh geometry={nodes.pCylinder176_Sput_ST_Metal_light_0.geometry} material={materials.Sput_ST_Metal_light} />
            <mesh geometry={nodes.pCylinder194_Sput_ST_Metal_light_0.geometry} material={materials.Sput_ST_Metal_light} />
            <mesh geometry={nodes.pCylinder195_Sput_ST_Metal_light_0.geometry} material={materials.Sput_ST_Metal_light} />
            <mesh geometry={nodes.pCylinder119_Sput_ST_Metal_Dark_0.geometry} material={materials.Sput_ST_Metal_Dark} />
            <mesh geometry={nodes.pCylinder122_Sput_ST_Metal_light_0.geometry} material={materials.Sput_ST_Metal_light} />
            <mesh geometry={nodes.pCylinder125_Sput_ST_Metal_light_0.geometry} material={materials.Sput_ST_Metal_light} />
            <mesh geometry={nodes.pCylinder124_Sput_ST_Metal_Dark_0.geometry} material={materials.Sput_ST_Metal_Dark} />
            <mesh geometry={nodes.pCylinder121_Sput_ST_Metal_light_0.geometry} material={materials.Sput_ST_Metal_light} />
            <mesh geometry={nodes.pCylinder123_Sput_ST_Metal_light_0.geometry} material={materials.Sput_ST_Metal_light} />
            <mesh geometry={nodes.pCylinder119_Sput_ST_Metal_Dark_0_1.geometry} material={materials.Sput_ST_Metal_Dark} />
            <mesh geometry={nodes.pCylinder122_Sput_ST_Metal_light_0_1.geometry} material={materials.Sput_ST_Metal_light} />
            <mesh geometry={nodes.pCylinder125_Sput_ST_Metal_light_0_1.geometry} material={materials.Sput_ST_Metal_light} />
            <mesh geometry={nodes.pCylinder124_Sput_ST_Metal_Dark_0_1.geometry} material={materials.Sput_ST_Metal_Dark} />
            <mesh geometry={nodes.pCylinder121_Sput_ST_Metal_light_0_1.geometry} material={materials.Sput_ST_Metal_light} />
            <mesh geometry={nodes.pCylinder123_Sput_ST_Metal_light_0_1.geometry} material={materials.Sput_ST_Metal_light} />
            <mesh geometry={nodes.pCube162_Sput_Gold_Back_0.geometry} material={materials.Sput_Gold_Back} />
            <mesh geometry={nodes.pCube162_Sput_ST_Metal_0.geometry} material={materials.Sput_ST_Metal} />
            <mesh geometry={nodes.pCylinder64_Sput_ST_Metal_0.geometry} material={materials.Sput_ST_Metal} />
            <mesh geometry={nodes.pCylinder64_Sput_ST_Metal_Light_0.geometry} material={materials.Sput_ST_Metal_Light} />
            <mesh geometry={nodes.pCylinder65_Sput_ST_Metal_0.geometry} material={materials.Sput_ST_Metal} />
            <mesh geometry={nodes.pCylinder65_Sput_ST_Metal_Light_0.geometry} material={materials.Sput_ST_Metal_Light} />
            <mesh geometry={nodes.pCylinder64_Sput_ST_Metal_0_1.geometry} material={materials.Sput_ST_Metal} />
            <mesh geometry={nodes.pCylinder64_Sput_ST_Metal_Light_0_1.geometry} material={materials.Sput_ST_Metal_Light} />
            <mesh geometry={nodes.pCylinder65_Sput_ST_Metal_0_1.geometry} material={materials.Sput_ST_Metal} />
            <mesh geometry={nodes.pCylinder65_Sput_ST_Metal_Light_0_1.geometry} material={materials.Sput_ST_Metal_Light} />
            <mesh geometry={nodes.pCylinder64_Sput_ST_Metal_0_2.geometry} material={materials.Sput_ST_Metal} />
            <mesh geometry={nodes.pCylinder64_Sput_ST_Metal_Light_0_2.geometry} material={materials.Sput_ST_Metal_Light} />
            <mesh geometry={nodes.pCylinder65_Sput_ST_Metal_0_2.geometry} material={materials.Sput_ST_Metal} />
            <mesh geometry={nodes.pCylinder65_Sput_ST_Metal_Light_0_2.geometry} material={materials.Sput_ST_Metal_Light} />
            <mesh geometry={nodes.pCylinder64_Sput_ST_Metal_0_3.geometry} material={materials.Sput_ST_Metal} />
            <mesh geometry={nodes.pCylinder64_Sput_ST_Metal_Light_0_3.geometry} material={materials.Sput_ST_Metal_Light} />
            <mesh geometry={nodes.pCylinder65_Sput_ST_Metal_0_3.geometry} material={materials.Sput_ST_Metal} />
            <mesh geometry={nodes.pCylinder65_Sput_ST_Metal_Light_0_3.geometry} material={materials.Sput_ST_Metal_Light} />
            <mesh geometry={nodes.pCylinder64_Sput_ST_Metal_0_4.geometry} material={materials.Sput_ST_Metal} />
            <mesh geometry={nodes.pCylinder64_Sput_ST_Metal_Light_0_4.geometry} material={materials.Sput_ST_Metal_Light} />
            <mesh geometry={nodes.pCylinder65_Sput_ST_Metal_0_4.geometry} material={materials.Sput_ST_Metal} />
            <mesh geometry={nodes.pCylinder65_Sput_ST_Metal_Light_0_4.geometry} material={materials.Sput_ST_Metal_Light} />
            <mesh geometry={nodes.pCylinder64_Sput_ST_Metal_0_5.geometry} material={materials.Sput_ST_Metal} />
            <mesh geometry={nodes.pCylinder64_Sput_ST_Metal_Light_0_5.geometry} material={materials.Sput_ST_Metal_Light} />
            <mesh geometry={nodes.pCylinder65_Sput_ST_Metal_0_5.geometry} material={materials.Sput_ST_Metal} />
            <mesh geometry={nodes.pCylinder65_Sput_ST_Metal_Light_0_5.geometry} material={materials.Sput_ST_Metal_Light} />
            <mesh geometry={nodes.pCube118_Sput_ST_Metal_Light_0.geometry} material={materials.Sput_ST_Metal_Light} />
            <mesh geometry={nodes.pCube117_Sput_ST_Metal_Light_0.geometry} material={materials.Sput_ST_Metal_Light} />
            <mesh geometry={nodes.pCube116_Sput_ST_Metal_Light_0.geometry} material={materials.Sput_ST_Metal_Light} />
            <mesh geometry={nodes.pCube115_Sput_ST_Metal_Light_0.geometry} material={materials.Sput_ST_Metal_Light} />
            <mesh geometry={nodes.pCube114_Sput_ST_Metal_Light_0.geometry} material={materials.Sput_ST_Metal_Light} />
            <mesh geometry={nodes.pCylinder63_Sput_ST_Metal_0.geometry} material={materials.Sput_ST_Metal} />
            <mesh geometry={nodes.pCube113_Sput_ST_Metal_Light_0.geometry} material={materials.Sput_ST_Metal_Light} />
            <mesh geometry={nodes.pCylinder42_Sput_ST_Metal_0.geometry} material={materials.Sput_ST_Metal} />
            <mesh geometry={nodes.pCylinder42_Sput_ST_Metal_Dark_0.geometry} material={materials.Sput_ST_Metal_Dark} />
            <mesh geometry={nodes.pCylinder41_Sput_ST_Metal_Dark_0.geometry} material={materials.Sput_ST_Metal_Dark} />
            <mesh geometry={nodes.pCylinder56_Sput_ST_Metal_light_0.geometry} material={materials.Sput_ST_Metal_light} />
            <mesh geometry={nodes.pCylinder57_Sput_ST_Metal_light_0.geometry} material={materials.Sput_ST_Metal_light} />
            <mesh geometry={nodes.pCylinder58_Sput_ST_Metal_light_0.geometry} material={materials.Sput_ST_Metal_light} />
            <mesh geometry={nodes.pCylinder59_Sput_ST_Metal_Dark_02_0.geometry} material={materials.Sput_ST_Metal_Dark_02} />
            <mesh geometry={nodes.pCylinder60_Sput_ST_Metal_light_0.geometry} material={materials.Sput_ST_Metal_light} />
            <mesh geometry={nodes.pCylinder77_Sput_ST_Metal_light_0.geometry} material={materials.Sput_ST_Metal_light} />
            <mesh geometry={nodes.pCylinder79_Sput_ST_Metal_light_0.geometry} material={materials.Sput_ST_Metal_light} />
            <mesh geometry={nodes.pCylinder78_Sput_ST_Metal_light_0.geometry} material={materials.Sput_ST_Metal_light} />
            <mesh geometry={nodes.pCylinder76_Sput_ST_Metal_light_0.geometry} material={materials.Sput_ST_Metal_light} />
            <mesh geometry={nodes.pCylinder80_Sput_ST_Metal_light_0.geometry} material={materials.Sput_ST_Metal_light} />
            <mesh geometry={nodes.pCylinder82_Sput_ST_Metal_light_0.geometry} material={materials.Sput_ST_Metal_light} />
            <mesh geometry={nodes.pCylinder81_Sput_ST_Metal_light_0.geometry} material={materials.Sput_ST_Metal_light} />
            <mesh geometry={nodes.pCylinder66_Sput_ST_Metal_light_0.geometry} material={materials.Sput_ST_Metal_light} />
            <mesh geometry={nodes.pCube86_Sput_ST_Metal_Dark_0.geometry} material={materials.Sput_ST_Metal_Dark} />
            <mesh geometry={nodes.pCube86_Sput_ST_Disk_0.geometry} material={materials.Sput_ST_Disk} />
            <mesh geometry={nodes.pCube86_Sput_ST_Metal_Dark_02_0.geometry} material={materials.Sput_ST_Metal_Dark_02} />
            <mesh geometry={nodes.pCylinder75_Sput_ST_Metal_0.geometry} material={materials.Sput_ST_Metal} position={[0.01, 0, 0]} />
            <mesh geometry={nodes.pCylinder62_Sput_ST_Metal_0.geometry} material={materials.Sput_ST_Metal} />
            <mesh geometry={nodes.pCylinder61_Sput_ST_Metal_0.geometry} material={materials.Sput_ST_Metal} />
            <mesh geometry={nodes.pCube95_Sput_ST_Metal_0.geometry} material={materials.Sput_ST_Metal} />
            <mesh geometry={nodes.pCube140_Sput_ST_Metal_Dark_0.geometry} material={materials.Sput_ST_Metal_Dark} />
            <mesh geometry={nodes.pCylinder112_Sput_ST_Metal_Gold_0.geometry} material={materials.Sput_ST_Metal_Gold} />
            <mesh geometry={nodes.pCylinder113_Sput_ST_Metal_Gold_0.geometry} material={materials.Sput_ST_Metal_Gold} />
            <mesh geometry={nodes.pCube144_Sput_ST_Metal_Light_0.geometry} material={materials.Sput_ST_Metal_Light} />
            <mesh geometry={nodes.group8_pCube96_Sput_ST_Metal_Dark_0.geometry} material={materials.Sput_ST_Metal_Dark} />
            <mesh geometry={nodes.pCube141_Sput_ST_Metal_Light_0.geometry} material={materials.Sput_ST_Metal_Light} />
            <mesh geometry={nodes.pCylinder110_Sput_ST_Metal_light_0.geometry} material={materials.Sput_ST_Metal_light} />
            <mesh geometry={nodes.pCylinder109_Sput_ST_Metal_light_0.geometry} material={materials.Sput_ST_Metal_light} />
            <mesh geometry={nodes.pCylinder39_Sput_ST_Metal_Dark_02_0.geometry} material={materials.Sput_ST_Metal_Dark_02} />
            <mesh geometry={nodes.pCylinder111_Sput_ST_Metal_Dark_02_0.geometry} material={materials.Sput_ST_Metal_Dark_02} />
            <mesh geometry={nodes.pCube95_Sput_ST_Metal_0_1.geometry} material={materials.Sput_ST_Metal} />
            <mesh geometry={nodes.pCube140_Sput_ST_Metal_Dark_0_1.geometry} material={materials.Sput_ST_Metal_Dark} />
            <mesh geometry={nodes.pCylinder112_Sput_ST_Metal_Gold_0_1.geometry} material={materials.Sput_ST_Metal_Gold} />
            <mesh geometry={nodes.pCylinder113_Sput_ST_Metal_Gold_0_1.geometry} material={materials.Sput_ST_Metal_Gold} />
            <mesh geometry={nodes.pCube144_Sput_ST_Metal_Light_0_1.geometry} material={materials.Sput_ST_Metal_Light} />
            <mesh geometry={nodes.group8_pCube96_Sput_ST_Metal_Dark_0_1.geometry} material={materials.Sput_ST_Metal_Dark} />
            <mesh geometry={nodes.pCube141_Sput_ST_Metal_Light_0_1.geometry} material={materials.Sput_ST_Metal_Light} />
            <mesh geometry={nodes.pCylinder110_Sput_ST_Metal_light_0_1.geometry} material={materials.Sput_ST_Metal_light} />
            <mesh geometry={nodes.pCylinder109_Sput_ST_Metal_light_0_1.geometry} material={materials.Sput_ST_Metal_light} />
            <mesh geometry={nodes.pCylinder39_Sput_ST_Metal_Dark_02_0_1.geometry} material={materials.Sput_ST_Metal_Dark_02} />
            <mesh geometry={nodes.pCylinder111_Sput_ST_Metal_Dark_02_0_1.geometry} material={materials.Sput_ST_Metal_Dark_02} />
            <mesh geometry={nodes.pCylinder233_Sput_Trubka_Or_0.geometry} material={materials.Sput_Trubka_Or} />
            <mesh geometry={nodes.pCylinder234_Sput_ST_Metal_Dark_0.geometry} material={materials.Sput_ST_Metal_Dark} />
            <mesh geometry={nodes.pCylinder234_Sput_ST_Metal_0.geometry} material={materials.Sput_ST_Metal} />
            <mesh geometry={nodes.pCube101_Sput_ST_Metal_Dark_0.geometry} material={materials.Sput_ST_Metal_Dark} />
            <mesh geometry={nodes.pCube104_Sput_ST_Metal_Light_0.geometry} material={materials.Sput_ST_Metal_Light} />
          </group>
        </group>
      </group>
    </group>
  )
}
